version: '3.9'

services:
  clickhouse-server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d
      - ./src/main/resources/db/ddl:/var/lib/clickhouse/user_files/ddl

  clickhouse-client:
    image: yandex/clickhouse-client
